# Generated by Django 4.1 on 2022-09-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0007_jobs_emailaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='quaification',
            new_name='quailfication',
        ),
    ]
