# Generated by Django 4.1 on 2022-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0009_appliedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstext', models.TextField()),
                ('newsdate', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='addresss',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='contacno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='keyskills',
            new_name='keyskill',
        ),
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='qualifications',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='quailfication',
            new_name='qualification',
        ),
        migrations.AlterField(
            model_name='employer',
            name='cpemailaddress',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='posteddate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='posteddate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
