# Generated by Django 4.1 on 2022-09-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0010_news_rename_addresss_appliedjobs_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='keyskill',
            new_name='keyskills',
        ),
    ]
